name: BRL Solutions
url: ""
permalink: /:collection/:name/

collections:
  projects:
    output: true
    sort_by: project-no

defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: "assets/img/projects"
    values:
      project: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll_picture_tag

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/