name: BRL Solutions
url: ""
permalink: /:collection/:name/

collections:
  projects:
    output: true
    sort_by: id

picture:
  fast_build: true

defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: "assets/img/projects"
    values:
      project: true

# staticman configuration
staticman_url: https://brl-staticman.herokuapp.com/v2/entry/net-solution/brl-solutions/main/reviews

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll_picture_tag
  - jekyll-loading-lazy

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/