# Global Variables
name: BRL Solutions
url: ""
permalink: /:collection/:name/

# Collections
collections:
  projects:
    output: true
    sort_by: project-no

# Defaults
defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: "assets/img/projects"
    values:
      project: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/