locations:
  - Monmouthshire
  - Gloucestershire
  - Herefordshire
  - Bristol
  - Vale of Glamorgan

services:
  - Building
  - Stone Walls
  - Brick Walls
  - Plastering
  - Rendering
  - Demolition
  - Windows & Doors
  - Roofing
  - Fascias & Soffits
  - Patios
  - Decking
  - Fencing
  - Garden Gates
  - Driveway Gates

timetable:
  Mon: 9:00 AM - 6:00 PM
  Tue: 9:00 AM - 6:00 PM
  Wed: 9:00 AM - 6:00 PM
  Thu: 9:00 AM - 6:00 PM
  Fri: 9:00 AM - 6:00 PM
  Sat: 10:00 AM - 4:00 PM
  Sun: 10:00 AM - 4:00 PM
