locations:
  - Monmouthshire
  - Gloucestershire
  - Herefordshire
  - Bristol
  - Vale of Glamorgan

services:
  - Building
  - Stone Walls
  - Brick Walls
  - Plastering
  - Rendering
  - Demolition
  - Windows & Doors
  - Roofing
  - Fascias & Soffits
  - Patios
  - Decking
  - Fencing
  - Garden Gates
  - Driveway Gates