- id: building
  name: Building

- id: stone_walls
  name: Stone Walls

- id: brick_walls
  name: Brick Walls

- id: plastering
  name: Plastering

- id: rendering
  name: Rendering

- id: demolition
  name: Demolition

- id: windows_doors
  name: Windows & Doors

- id: roofing
  name: Roofing

- id: fascias_soffits
  name: Fascias & Soffits

- id: patios
  name: Patios

- id: decking
  name: Decking

- id: fencing
  name: Fencing

- id: garden_gates
  name: Garden Gates

- id: driveway_gates
  name: Driveway gates